### PR TITLE
Adding animation to cursor click

### PR DESCRIPTION
**Pull request by Tokinh0**
first pull request at this shit

### CODE REVIEW

**Comment by hjJunior** [comment]
@Tokinh0 pls improve your pr request description adding final result image

**Review by hjJunior — COMMENTED** [review]
@Tokinh0 pls improve your pr request description adding final result image

**Review by hjJunior — COMMENTED** [review]
Why are there `Mouse.cur` at `assets/images` and another one `assets/stylesheets/Mouse.cur`

**Review by Kutomore — CHANGES_REQUESTED** [review]
This will not pass since all it does is make the cursor, you should re-do it, I suggest making it so when you click on the screen you change the cursor to a regular cursor but with some fluff above it, to simulate some sort of animation, but as is, it will not pass

**Comment by Tokinh0** [comment]
okay, i will make those changes later wen i have some extra time, then i up to git.

**Pull request closed without merging**
